# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/gtaxlwifi/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter gtaxlwifi gtanotexlwifi,$(TARGET_DEVICE)),)

endif
